import { z } from "zod";

import { isCrmSyncInterval } from "@/modules/crm/crm-connector-sync";
import {
  crmImportProviderModes,
  crmImportProviders,
  crmPullAuthenticationMethods,
  crmPullProviderDefaultAuthenticationMethod,
  isCrmPullProvider,
  supportsCrmPullAuthenticationMethod,
} from "@/modules/crm/crm-import-providers";

function emptyToNull(value: unknown): unknown {
  return value === undefined || (typeof value === "string" && value.trim() === "") ? null : value;
}

function checkbox(value: unknown): boolean {
  return value === true || value === "true" || value === "on" || value === "1";
}

const optionalText = (max: number) =>
  z.preprocess(emptyToNull, z.string().trim().max(max).nullable());

function isAllowedSalesforceHost(value: string, hosts: Set<string>): boolean {
  try {
    const url = new URL(value);
    return url.protocol === "https:" && hosts.has(url.hostname) && url.pathname === "/";
  } catch {
    return false;
  }
}

export const crmConnectionCreateSchema = z
  .object({
    provider: z.enum(crmImportProviders),
    name: z.string().trim().min(2, "Enter a connection name.").max(100),
    accountReference: optionalText(180),
    authenticationMethod: z.preprocess(
      emptyToNull,
      z.enum(crmPullAuthenticationMethods).nullable(),
    ),
    accessToken: optionalText(8_000),
    oauthClientId: optionalText(1_000),
    oauthClientSecret: optionalText(8_000),
    secondarySecret: optionalText(8_000),
    webhookKey: optionalText(500),
    instanceUrl: optionalText(500),
    salesforceLoginUrl: optionalText(100),
    apiVersion: optionalText(30),
    region: optionalText(30),
    syncEnabled: z.preprocess(checkbox, z.boolean()).default(false),
    syncIntervalMinutes: z.coerce
      .number()
      .int()
      .refine(isCrmSyncInterval, {
        message: "Choose a supported sync interval.",
      })
      .default(60),
  })
  .superRefine((value, context) => {
    const mode = crmImportProviderModes[value.provider];
    if (mode === "pull" && isCrmPullProvider(value.provider)) {
      const method =
        value.authenticationMethod ?? crmPullProviderDefaultAuthenticationMethod[value.provider];
      if (!supportsCrmPullAuthenticationMethod(value.provider, method)) {
        context.addIssue({
          code: "custom",
          path: ["authenticationMethod"],
          message: "Choose an authentication method supported by this provider.",
        });
      }
      if (method === "api_token") {
        if (!value.accessToken) {
          context.addIssue({
            code: "custom",
            path: ["accessToken"],
            message: "Add the API token generated by the client CRM account.",
          });
        }
        if (value.oauthClientId || value.oauthClientSecret) {
          context.addIssue({
            code: "custom",
            path: ["oauthClientId"],
            message: "API-token connections do not use OAuth client credentials.",
          });
        }
      } else if (method === "client_oauth") {
        if (!value.oauthClientId) {
          context.addIssue({
            code: "custom",
            path: ["oauthClientId"],
            message: "Add the client-owned OAuth application ID.",
          });
        }
        if (!value.oauthClientSecret) {
          context.addIssue({
            code: "custom",
            path: ["oauthClientSecret"],
            message: "Add the client-owned OAuth application secret.",
          });
        }
        if (value.accessToken) {
          context.addIssue({
            code: "custom",
            path: ["accessToken"],
            message: "OAuth connections receive access tokens from the provider callback.",
          });
        }
      } else if (value.accessToken || value.oauthClientId || value.oauthClientSecret) {
        context.addIssue({
          code: "custom",
          path: ["authenticationMethod"],
          message: "Agency-managed OAuth uses only server environment credentials.",
        });
      }
    }
    if (value.provider === "meta_lead_ads") {
      if (!value.accessToken) {
        context.addIssue({
          code: "custom",
          path: ["accessToken"],
          message: "Add a Meta Page access token.",
        });
      }
      if (!value.secondarySecret) {
        context.addIssue({
          code: "custom",
          path: ["secondarySecret"],
          message: "Add the Meta app secret.",
        });
      }
    }
    if (value.provider === "salesforce" && value.instanceUrl) {
      try {
        const url = new URL(value.instanceUrl);
        if (url.protocol !== "https:" || !/(^|\.)salesforce\.com$/i.test(url.hostname)) {
          throw new Error("invalid");
        }
      } catch {
        context.addIssue({
          code: "custom",
          path: ["instanceUrl"],
          message: "Use an HTTPS salesforce.com instance URL or leave it empty for OAuth.",
        });
      }
    }
    if (
      value.provider === "salesforce" &&
      value.salesforceLoginUrl &&
      !isAllowedSalesforceHost(
        value.salesforceLoginUrl,
        new Set(["login.salesforce.com", "test.salesforce.com"]),
      )
    ) {
      context.addIssue({
        code: "custom",
        path: ["salesforceLoginUrl"],
        message: "Choose the Salesforce production or sandbox login origin.",
      });
    }
  })
  .transform((value) => ({
    ...value,
    authenticationMethod:
      isCrmPullProvider(value.provider) && !value.authenticationMethod
        ? crmPullProviderDefaultAuthenticationMethod[value.provider]
        : value.authenticationMethod,
  }));

export const crmConnectionIdSchema = z.object({ connectionId: z.uuid() });

export const crmConnectionStatusSchema = crmConnectionIdSchema.extend({
  status: z.enum(["active", "paused"]),
});

export const crmConnectionScheduleSchema = crmConnectionIdSchema.extend({
  syncEnabled: z.preprocess(checkbox, z.boolean()),
  syncIntervalMinutes: z.coerce.number().int().refine(isCrmSyncInterval, {
    message: "Choose a supported sync interval.",
  }),
});

export const crmConnectionCredentialRotationSchema = crmConnectionIdSchema.extend({
  accessToken: optionalText(8_000),
  secondarySecret: optionalText(8_000),
  webhookKey: optionalText(500),
});

export const crmConnectionNotificationSchema = z.object({
  notificationId: z.uuid(),
});

const webhookIdentifier = z.union([z.string().trim().min(1).max(500), z.number().finite().safe()]);
const webhookSecret = z.string().min(1).max(500);
const webhookFieldValue = z.string().max(20_000);

export const crmGoogleAdsWebhookPayloadSchema = z
  .strictObject({
    lead_id: webhookIdentifier.optional(),
    api_version: z.string().trim().min(1).max(30).optional(),
    form_id: webhookIdentifier.optional(),
    campaign_id: webhookIdentifier.optional(),
    adgroup_id: webhookIdentifier.optional(),
    creative_id: webhookIdentifier.optional(),
    gcl_id: z.string().max(2_000).optional(),
    google_key: webhookSecret.optional(),
    webhook_key: webhookSecret.optional(),
    is_test: z.union([z.boolean(), z.literal("true"), z.literal("false")]).optional(),
    lead_event_time: z.union([z.string().max(100), z.number().finite()]).optional(),
    user_column_data: z
      .array(
        z.strictObject({
          column_id: z.string().trim().min(1).max(200).optional(),
          column_name: z.string().trim().min(1).max(200).optional(),
          string_value: webhookFieldValue.optional(),
          column_value: webhookFieldValue.optional(),
        }),
      )
      .max(200)
      .optional(),
  })
  .refine((payload) => Boolean(payload.google_key || payload.webhook_key), {
    path: ["google_key"],
    message: "Google Ads webhook authentication is required.",
  });

const crmMetaLeadValueSchema = z.strictObject({
  leadgen_id: webhookIdentifier,
  page_id: webhookIdentifier.optional(),
  form_id: webhookIdentifier.optional(),
  ad_id: webhookIdentifier.optional(),
  adgroup_id: webhookIdentifier.optional(),
  created_time: z.number().finite().safe().optional(),
});

export const crmMetaLeadAdsWebhookPayloadSchema = z.strictObject({
  object: z.literal("page"),
  entry: z
    .array(
      z.strictObject({
        id: webhookIdentifier.optional(),
        time: z.number().finite().safe().optional(),
        changes: z
          .array(
            z.strictObject({
              field: z.literal("leadgen").optional(),
              value: crmMetaLeadValueSchema,
            }),
          )
          .max(200)
          .optional(),
      }),
    )
    .max(200),
});

export const crmWebhookPayloadSchema = z.union([
  crmGoogleAdsWebhookPayloadSchema,
  crmMetaLeadAdsWebhookPayloadSchema,
]);

export const crmFileImportSchema = z.object({
  stageId: z.uuid(),
  ownerMembershipId: z.preprocess(emptyToNull, z.uuid().nullable()),
  duplicatePolicy: z.enum(["skip", "merge"]).default("skip"),
  sourceName: z.string().trim().min(2).max(100).default("Spreadsheet import"),
});

export interface CrmImportActionState {
  status: "idle" | "error" | "success";
  message?: string;
  fieldErrors?: Record<string, string[]>;
  oneTimeSecret?: string;
  connectionId?: string;
  oauthStartPath?: string;
}
